version: '3.3'
services:
  linguard:
    image: "ghcr.io/joseantmazonsb/linguard:stable"
    container_name: "linguard"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "${DATA_FOLDER:-/srv/linguard/data}:/data"
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      custom_network:
        ipv4_address: 172.18.0.2

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=america/bogota
      - SERVERURL=1.1.1.1 #optional
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - /root/wireguard:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      custom_network:
        ipv4_address: 172.18.0.3

networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
